import Head from "next/head";
import Header from "./header";
import Sidebar from "./sidebar";

function Layout({ children }: { children: React.ReactNode }) {
  const navigation = [
    { title: "Inventaire", href: "/inventory" },
    { title: "Pokédex", href: "/pokedex" },
    { title: "Combat", href: "/combat" },
  ];

  return (
    <div className="bg-gray-100 min-h-screen">
      <Head>
        <title>Cent Percent Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="min-h-screen flex">
        <Sidebar navigation={navigation} />

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto">
            <div className="py-8">{children}</div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default Layout;
