import Head from "next/head";
import Header from "./header";
import Sidebar from "./sidebar";

function Layout({ children }: { children: React.ReactNode }) {
  const navigation = [
    { title: "Inventaire", href: "/" },
    { title: "Pokédex", href: "/pokedex" },
    { title: "Combat", href: "/combat" },
  ];

  return (
    <>
      <Head>
        <title>Cent Percent Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main
        className="flex min-h-screen dark:bg-stone-800"
        suppressHydrationWarning
      >
        <Sidebar navigation={navigation} />

        <div className="w-full px-4 sm:px-6 lg:px-8">
          <div className="py-8">{children}</div>
        </div>
      </main>
    </>
  );
}

export default Layout;
